name: sourch_ch_test
on: 
  workflow_dispatch:
    inputs:
      who_am_i:
        description: Name of someone who trigger this workflow
        required: true
        type: text
      what_to_do:
        description: Select one to do
        required: true
        type: choice
        options:
          - test
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up php5.6
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.6
          extensions: grpc.so
      - name : Check php version
        run: |
          php -v

